### ISSUE TITLE
可以开源了吗，大佬

### ISSUE THREAD

**Issue by Phil610351** [tianpeiyang/MAPTF_code#2]
可以开源了吗，大佬

**Comment by Phil610351** [comment]
可以开源了吗，大佬 12月份了

**Comment by Phil610351** [comment]
可以开源了吗，大佬 12月份了

**Comment by Phil610351** [comment]
可以开源了吗，大佬 12月份了

**Comment by Phil610351** [comment]
可以开源了吗，大佬 12月份了

**Comment by Phil610351** [comment]
可以开源了吗，大佬

**Comment by Phil610351** [comment]
可以开源了吗，大佬

**Comment by Phil610351** [comment]
可以开源了吗，大佬

**Comment by Phil610351** [comment]
可以开源了吗，大佬

**Comment by Phil610351** [comment]
可以开源了吗，大佬

**Comment by Phil610351** [comment]
可以开源了吗，大佬

**Comment by Phil610351** [comment]
可以开源了吗，大佬

**Comment by Phil610351** [comment]
可以开源了吗，大佬

**Comment by Phil610351** [comment]
可以开源了吗，大佬

**Comment by Phil610351** [comment]
可以开源了吗，大佬

**Comment by Phil610351** [comment]
Don’t worry, big guys. Tianpei said that it will open source in December and it will be open source in December. Don’t worry, big guys.

**Comment by ShirleyPmy** [comment]
马上1月了诶…

**Comment by Phil610351** [comment]
杨天培大佬说了开源，就一定会开源，大家再等等。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月29日(周三) 下午4:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tianpeiyang/MAPTF_code] 可以开源了吗，大佬 (Issue #2)




 
马上1月了诶…
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Phil610351** [comment]
该 开源了

**Comment by Phil610351** [comment]
该 开源了

**Comment by Phil610351** [comment]
该 开源了

**Comment by Phil610351** [comment]
说好的开源的呢
